package sims;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author owner
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelSelectTab = new javax.swing.JTabbedPane();
        modify = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studID = new javax.swing.JTextField();
        modStudent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dispSelected = new javax.swing.JTextArea();
        addNew = new javax.swing.JPanel();
        stuNameLabel = new javax.swing.JLabel();
        passwLabel = new javax.swing.JLabel();
        studName = new javax.swing.JTextField();
        passw = new javax.swing.JTextField();
        submitNew = new javax.swing.JButton();
        tab3 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();

        studID.setText("Student ID");

        modStudent.setMnemonic('s');
        modStudent.setText("Select");
        modStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modStudentMouseClicked(evt);
            }
        });

        dispSelected.setColumns(20);
        dispSelected.setRows(5);
        jScrollPane2.setViewportView(dispSelected);

        javax.swing.GroupLayout modifyLayout = new javax.swing.GroupLayout(modify);
        modify.setLayout(modifyLayout);
        modifyLayout.setHorizontalGroup(
            modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifyLayout.createSequentialGroup()
                        .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modStudent)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        modifyLayout.setVerticalGroup(
            modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelSelectTab.addTab("Modify", modify);

        addNew.setToolTipText("");

        stuNameLabel.setText("Student Name");

        passwLabel.setText("Password");

        studName.setText("Student's full name"); // NOI18N
        studName.setToolTipText("Enter the Student's full name");

        passw.setText("Enter Password");

        submitNew.setMnemonic('s');
        submitNew.setText("Submit");
        submitNew.setToolTipText("Click to submit new student information");
        submitNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewLayout = new javax.swing.GroupLayout(addNew);
        addNew.setLayout(addNewLayout);
        addNewLayout.setHorizontalGroup(
            addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stuNameLabel)
                    .addComponent(passwLabel))
                .addGap(62, 62, 62)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitNew)
                .addContainerGap())
        );
        addNewLayout.setVerticalGroup(
            addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuNameLabel)
                    .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwLabel)
                    .addComponent(passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(submitNew)
                .addContainerGap())
        );

        panelSelectTab.addTab("Add New", addNew);

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        panelSelectTab.addTab("tab3", tab3);

        exit.setMnemonic('x');
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelSelectTab))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSelectTab, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * this method will pull the student ID from the text field, pass it to the database
 * and populate the text area with the values associated.
 * @param evt the mouse event 
 */
    private void modStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modStudentMouseClicked
        // TODO add your handling code here:
        //pull the student ID from the text field, pass it to the database and
        //populate the text area with the values from the database
        
    }//GEN-LAST:event_modStudentMouseClicked
/**
 * this method will pull text from the JTextFields on the Add New tab and will 
 * make an entry into the database.
 * @param evt the mouse event
 */
    private void submitNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewActionPerformed
        // TODO add your handling code here:
        // pull text from the JTextFields and insert into the database
    }//GEN-LAST:event_submitNewActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel addNew;
    public javax.swing.JTextArea dispSelected;
    public javax.swing.JButton exit;
    public javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton modStudent;
    public javax.swing.JPanel modify;
    public javax.swing.JTabbedPane panelSelectTab;
    public javax.swing.JTextField passw;
    public javax.swing.JLabel passwLabel;
    public javax.swing.JLabel stuNameLabel;
    public javax.swing.JTextField studID;
    public javax.swing.JTextField studName;
    public javax.swing.JButton submitNew;
    public javax.swing.JPanel tab3;
    // End of variables declaration//GEN-END:variables
}
