package sims;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author owner
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        modify = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studID = new javax.swing.JTextField();
        modStudent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dispSelected = new javax.swing.JTextArea();
        addNew = new javax.swing.JPanel();
        stuNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studName = new javax.swing.JTextField();
        passw = new javax.swing.JTextField();
        submitNew = new javax.swing.JButton();

        studID.setText("Student ID");

        modStudent.setText("Select");
        modStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modStudentMouseClicked(evt);
            }
        });

        dispSelected.setColumns(20);
        dispSelected.setRows(5);
        jScrollPane2.setViewportView(dispSelected);

        javax.swing.GroupLayout modifyLayout = new javax.swing.GroupLayout(modify);
        modify.setLayout(modifyLayout);
        modifyLayout.setHorizontalGroup(
            modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifyLayout.createSequentialGroup()
                        .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modStudent)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        modifyLayout.setVerticalGroup(
            modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modify", modify);

        addNew.setToolTipText("");

        stuNameLabel.setText("Student Name");

        jLabel2.setText("Password");

        studName.setText("Student's full name"); // NOI18N
        studName.setToolTipText("Enter the Student's full name");

        passw.setText("Enter Password");

        submitNew.setMnemonic('s');
        submitNew.setText("Submit");
        submitNew.setToolTipText("Click to submit new student information");

        javax.swing.GroupLayout addNewLayout = new javax.swing.GroupLayout(addNew);
        addNew.setLayout(addNewLayout);
        addNewLayout.setHorizontalGroup(
            addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stuNameLabel)
                    .addComponent(jLabel2))
                .addGap(62, 62, 62)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitNew)
                .addContainerGap())
        );
        addNewLayout.setVerticalGroup(
            addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuNameLabel)
                    .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(submitNew)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add New", addNew);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modStudentMouseClicked
        // TODO add your handling code here:
        //pull the student ID from the text field, pass it to the database and
        //populate the text area with the values from the database
        
    }//GEN-LAST:event_modStudentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addNew;
    private javax.swing.JTextArea dispSelected;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modStudent;
    private javax.swing.JPanel modify;
    private javax.swing.JTextField passw;
    private javax.swing.JLabel stuNameLabel;
    private javax.swing.JTextField studID;
    private javax.swing.JTextField studName;
    private javax.swing.JButton submitNew;
    // End of variables declaration//GEN-END:variables
}
