/**
 * This class displays a frame from which an admin user can view all students 
 * enrolled, select a student to modify, add courses to selected student, 
 * delete courses for selected student, and add grades to the courses. 
 * This class is called from mainFrame accesses Db and Login, and makes changes 
 * to the values in the connected database.
 * 
 */
package sims;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author owner
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        setLocationRelativeTo(null);
        dispTableInfo();
        getRootPane().setDefaultButton(modStudent);
        String[] chooseCourse = {"4315 Operating Systems","2302 Digital Logic",
                "3308 Numerical Methods","3321 Software Engineering","3326 Network Security",
        "4328 Parallel Computing"};
        fillStudentCombo();
        fillStudCombo();
        fillStudentSelectionCombo();
        warningMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane adminTabbedPane = new javax.swing.JTabbedPane();
        modify = new javax.swing.JPanel();
        stuID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        modStudent = new javax.swing.JButton();
        selectStudentDisp = new javax.swing.JScrollPane();
        selStudTable = new javax.swing.JTable();
        allStudentDisp = new javax.swing.JScrollPane();
        dispAllTable = new javax.swing.JTable();
        addClass = new javax.swing.JButton();
        dispAllLabel = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        allCourseDisp = new javax.swing.JScrollPane();
        dispCourseTable = new javax.swing.JTable();
        courseLabel = new javax.swing.JLabel();
        courseList = new javax.swing.JComboBox<>();
        addGradesPanel = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        courseSelectLabel = new javax.swing.JLabel();
        examLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        gradeEntered = new javax.swing.JTextField();
        studentSelection = new javax.swing.JComboBox<>();
        courseSelection = new javax.swing.JComboBox<>();
        assignmentSelection = new javax.swing.JComboBox<>();
        changeGrade = new javax.swing.JButton();
        clearSelections = new javax.swing.JButton();
        warning = new javax.swing.JLabel();
        deleteClass = new javax.swing.JPanel();
        stuSelect = new javax.swing.JLabel();
        stuSel = new javax.swing.JComboBox<>();
        courseSel = new javax.swing.JLabel();
        courseSelect = new javax.swing.JComboBox<>();
        deleteCourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        delClassTable = new javax.swing.JTable();
        tableLabel = new javax.swing.JLabel();
        addNew = new javax.swing.JPanel();
        firstName = new javax.swing.JLabel();
        passwLabel = new javax.swing.JLabel();
        studFirstName = new javax.swing.JTextField();
        passw = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        lastName = new javax.swing.JLabel();
        studLastName = new javax.swing.JTextField();
        genIDLabel = new javax.swing.JLabel();
        deleteStudent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studSelection = new javax.swing.JComboBox<>();
        delStudent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        warningMessage = new javax.swing.JTextArea();
        exit = new javax.swing.JButton();
        previous = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator View - SIMS");
        setBackground(new java.awt.Color(165, 191, 217));

        adminTabbedPane.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        stuID.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        stuID.setToolTipText("Enter Student ID here");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Enter Student ID: ");

        modStudent.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        modStudent.setMnemonic('s');
        modStudent.setText("Select");
        modStudent.setToolTipText("Select a student to modify");
        modStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modStudentActionPerformed(evt);
            }
        });

        selStudTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        selectStudentDisp.setViewportView(selStudTable);

        dispAllTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        allStudentDisp.setViewportView(dispAllTable);

        addClass.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        addClass.setText("Add Class");
        addClass.setToolTipText("Add class to selected student");
        addClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassActionPerformed(evt);
            }
        });

        dispAllLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        dispAllLabel.setText("Enrolled Students:");

        clear.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        clear.setText("Clear");
        clear.setToolTipText("Clear student selection");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        dispCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        allCourseDisp.setViewportView(dispCourseTable);

        courseLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        courseLabel.setText("Active Courses");

        courseList.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        courseList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4315 Operating Systems", "2302 Digital Logic", "3308 Numerical Methods", "3321 Software Engineering", "3326 Network Security", "4328 Parallel Computing" }));
        courseList.setToolTipText("Select a Course to Add...");

        javax.swing.GroupLayout modifyLayout = new javax.swing.GroupLayout(modify);
        modify.setLayout(modifyLayout);
        modifyLayout.setHorizontalGroup(
            modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allStudentDisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                    .addComponent(selectStudentDisp)
                    .addComponent(allCourseDisp)
                    .addGroup(modifyLayout.createSequentialGroup()
                        .addGroup(modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(dispAllLabel)
                            .addComponent(courseLabel)
                            .addGroup(modifyLayout.createSequentialGroup()
                                .addComponent(stuID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseList, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(addClass, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        modifyLayout.setVerticalGroup(
            modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modStudent)
                    .addComponent(addClass)
                    .addComponent(clear)
                    .addComponent(courseList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectStudentDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(courseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allCourseDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dispAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allStudentDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adminTabbedPane.addTab("Modify", modify);

        studentLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        studentLabel.setText("Select Student: ");

        courseSelectLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        courseSelectLabel.setText("Select Course: ");

        examLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        examLabel.setText("Choose Assignment:");

        gradeLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        gradeLabel.setText("Enter Grade:");

        studentSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentSelectionItemStateChanged(evt);
            }
        });

        courseSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        assignmentSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "exam_one", "final_exam" }));

        changeGrade.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        changeGrade.setMnemonic('g');
        changeGrade.setText("Submit Grade");
        changeGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeGradeActionPerformed(evt);
            }
        });

        clearSelections.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        clearSelections.setText("Clear");
        clearSelections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSelectionsActionPerformed(evt);
            }
        });

        warning.setForeground(new java.awt.Color(228, 72, 72));
        warning.setText("Integer values only");

        javax.swing.GroupLayout addGradesPanelLayout = new javax.swing.GroupLayout(addGradesPanel);
        addGradesPanel.setLayout(addGradesPanelLayout);
        addGradesPanelLayout.setHorizontalGroup(
            addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addGradesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(gradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(examLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseSelectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addGradesPanelLayout.createSequentialGroup()
                        .addComponent(changeGrade)
                        .addGap(18, 18, 18)
                        .addComponent(clearSelections, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addGradesPanelLayout.createSequentialGroup()
                        .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assignmentSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gradeEntered))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(courseSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(534, Short.MAX_VALUE))
        );
        addGradesPanelLayout.setVerticalGroup(
            addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addGradesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warning))
                .addGap(28, 28, 28)
                .addGroup(addGradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeGrade)
                    .addComponent(clearSelections))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Add Grades", addGradesPanel);

        stuSelect.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        stuSelect.setText("Select Student: ");

        stuSel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        stuSel.setToolTipText("Select a student by ID number");
        stuSel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stuSelItemStateChanged(evt);
            }
        });

        courseSel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        courseSel.setText("Select Course:");

        courseSelect.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        courseSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseSelect.setToolTipText("Select course to delete");

        deleteCourse.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deleteCourse.setMnemonic('d');
        deleteCourse.setText("Delete");
        deleteCourse.setToolTipText("Delete selected course. This is not reversible.");
        deleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseActionPerformed(evt);
            }
        });

        delClassTable.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        delClassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        delClassTable.setName(""); // NOI18N
        jScrollPane1.setViewportView(delClassTable);

        tableLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tableLabel.setText("Registered Courses:");

        javax.swing.GroupLayout deleteClassLayout = new javax.swing.GroupLayout(deleteClass);
        deleteClass.setLayout(deleteClassLayout);
        deleteClassLayout.setHorizontalGroup(
            deleteClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteClassLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(deleteClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deleteClassLayout.createSequentialGroup()
                        .addGroup(deleteClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuSelect)
                            .addComponent(courseSel))
                        .addGap(80, 80, 80)
                        .addGroup(deleteClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuSel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        deleteClassLayout.setVerticalGroup(
            deleteClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteClassLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(deleteClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuSelect)
                    .addComponent(stuSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deleteClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseSel)
                    .addComponent(courseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(deleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(tableLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Delete Class", deleteClass);

        firstName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        firstName.setText("First Name: ");

        passwLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        passwLabel.setText("Password: ");

        submit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        submit.setMnemonic('b');
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        lastName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lastName.setText("Last Name");

        genIDLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        genIDLabel.setText("Generated ID:");

        javax.swing.GroupLayout addNewLayout = new javax.swing.GroupLayout(addNew);
        addNew.setLayout(addNewLayout);
        addNewLayout.setHorizontalGroup(
            addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submit)
                    .addGroup(addNewLayout.createSequentialGroup()
                        .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewLayout.createSequentialGroup()
                                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstName)
                                    .addComponent(passwLabel))
                                .addGap(18, 18, 18))
                            .addGroup(addNewLayout.createSequentialGroup()
                                .addComponent(lastName)
                                .addGap(26, 26, 26)))
                        .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studFirstName)
                            .addComponent(passw, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(studLastName))))
                .addGap(47, 47, 47)
                .addComponent(genIDLabel)
                .addContainerGap(574, Short.MAX_VALUE))
        );
        addNewLayout.setVerticalGroup(
            addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName)
                    .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genIDLabel)))
                .addGap(30, 30, 30)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastName)
                    .addComponent(studLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwLabel)
                    .addComponent(passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(submit)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Add Student", addNew);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Select Student: ");

        studSelection.setToolTipText("Select student to delete. This cannot be undone.");
        studSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studSelectionItemStateChanged(evt);
            }
        });

        delStudent.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        delStudent.setText("Delete");
        delStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStudentActionPerformed(evt);
            }
        });

        warningMessage.setColumns(20);
        warningMessage.setForeground(new java.awt.Color(217, 47, 47));
        warningMessage.setLineWrap(true);
        warningMessage.setRows(5);
        warningMessage.setText("This student cannot be removed from the system. Please delete the courses this student is enrolled in first.");
        jScrollPane2.setViewportView(warningMessage);

        javax.swing.GroupLayout deleteStudentLayout = new javax.swing.GroupLayout(deleteStudent);
        deleteStudent.setLayout(deleteStudentLayout);
        deleteStudentLayout.setHorizontalGroup(
            deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delStudent)
                    .addGroup(deleteStudentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(studSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        deleteStudentLayout.setVerticalGroup(
            deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStudentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(studSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delStudent)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Delete Student", deleteStudent);

        exit.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        exit.setMnemonic('x');
        exit.setText("Exit");
        exit.setToolTipText("Shutdown program");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        previous.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        previous.setText("Previous");
        previous.setToolTipText("Return to Login window");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(previous)
                        .addGap(18, 18, 18)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(previous))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void dispTableInfo(){
    	
        try{
            Connection conn = Db.java_db();
            String sql = "SELECT * FROM student_info";
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            dispAllTable.setModel(DbUtils.resultSetToTableModel(rs));             
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void modStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modStudentActionPerformed
        // TODO add your handling code here:
        int studID = Integer.parseInt(stuID.getText());
        stuID.setEditable(false);
        //send this studID to the database and return the info associated with it
        //and put in selStudTable
        
        dispCourseTablePop(studID);
        dispSelStudentTablePop(studID);
        
    }//GEN-LAST:event_modStudentActionPerformed

    private void dispSelStudentTablePop(int studID){
        try{
            Connection conn = Db.java_db();
            String sql = "SELECT * FROM student_info WHERE student_id = " + studID;
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            selStudTable.setModel(DbUtils.resultSetToTableModel(rs));
              
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    public void dispCourseTablePop(int studID){
        try{           
            Connection conn = Db.java_db();
            String sql = "SELECT * FROM courses WHERE student_id = " + studID;
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            dispCourseTable.setModel(DbUtils.resultSetToTableModel(rs));
              
            
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    /**
     * this button will add the student to the database and display the generated
     * student ID number.
     * @param evt 
     */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        int p = newIDGen();
        genIDLabel.setText("Generated ID: "+p);
        String first = studFirstName.getText();
        String last = studLastName.getText();
        int passq = Integer.parseInt(passw.getText());

        Login.addStudent(p, first, last, passq);
        dispTableInfo();
        fillStudentSelectionCombo();
    }//GEN-LAST:event_submitActionPerformed

    /**
     * This method will pull the values from the stuID JLabel and the selected value
     * from the courseList JComboBox, change them to integer values and pass them 
     * to the addClass method in the Login class.
     * @param evt the button click that initiates the action.
     */
    private void addClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassActionPerformed
        int idNum = Integer.parseInt(stuID.getText());              //the value for the student ID  
        int courseID; String p,q = null;
        String x = String.valueOf(courseList.getSelectedItem());
        if(x.length()>4){
            p = x.substring(0,4);
        }else{
            p =x;
        }
        if(x.length()>4){
            q = x.substring(5, x.length());
        }
        courseID = Integer.parseInt(p); String courseName = q;
        System.out.println(idNum+"\t"+ courseID);   //tests values to be passed in following method
        Login.addClass(idNum, courseID, courseName);
        dispCourseTablePop(idNum);
    }//GEN-LAST:event_addClassActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:
        new mainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_previousActionPerformed

    /**
     * This action listener is for the clear button on the Modify tab.
     * @param evt 
     */
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        stuID.setText("");
        stuID.setEditable(true);
    }//GEN-LAST:event_clearActionPerformed

    private void changeGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeGradeActionPerformed
        // TODO add your handling code here:
        //collect course_id from combobox
        int courseID; String p;
        String x = String.valueOf(courseSelection.getSelectedItem());
        if(x.length()>4){
            p = x.substring(0,4);
        }else{
            p =x;
        }
        courseID = Integer.parseInt(p);
        //collects the student_id from combobox
        int sdi = Integer.parseInt(String.valueOf(studentSelection.getSelectedItem()));
        //collect the selected assignment to add the grade to
        String asgn = String.valueOf(assignmentSelection.getSelectedItem());
        //collect grade to add
        int grade = Integer.parseInt(gradeEntered.getText());
        Login.addGrades(sdi, courseID, asgn, grade);
        dispCourseTablePop(sdi);
    }//GEN-LAST:event_changeGradeActionPerformed

    /**
     * this method will fill the courseSelection comboBox with data based on the 
     * studentSelection comboBox.
     */
    private void fillCourseCombo(){
        try{
            int sdi = Integer.parseInt(String.valueOf(studentSelection.getSelectedItem()));
            Connection conn = Db.java_db();
            String sql = "select * from courses where student_id = "+sdi;
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                String courseID = rs.getString("course_id");
                String courseName = rs.getString("course_name");
                courseSelection.addItem(courseID +" "+ courseName);
            }
            
        }catch(Exception w){
            System.out.println(w);
        }
    }
    
    private void fillDelCourseCombo(){
    try{
        int sdi = Integer.parseInt(String.valueOf(stuSel.getSelectedItem()));
        Connection conn = Db.java_db();
        String sql = "select * from courses where student_id = "+sdi;
        PreparedStatement pstmt = conn.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();

        while(rs.next()){
            String courseID = rs.getString("course_id");
            String courseName = rs.getString("course_name");
            courseSelect.addItem(courseID +" "+ courseName);
        }

    }catch(Exception w){
        System.out.println(w);
    }
}
    
    private void fillStudentCombo(){
        try{
            Connection conn = Db.java_db();
            String sql = "select * from student_info";
            PreparedStatement pstmt = conn.prepareStatement(sql);  
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                String studId = rs.getString("student_id");
                stuSel.addItem(studId);
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }
    
private void fillStudentSelectionCombo(){
    try{
        Connection conn = Db.java_db();
        String sql = "select * from student_info";
        PreparedStatement pstmt = conn.prepareStatement(sql);  
        ResultSet rs = pstmt.executeQuery();

        while(rs.next()){
            String studId = rs.getString("student_id");
            studentSelection.addItem(studId);
        }
    }catch(Exception e){
        System.out.println(e);
    }

}
    
    private void fillStudCombo(){
        try{
            Connection conn = Db.java_db();
            String sql = "select * from student_info";
            PreparedStatement pstmt = conn.prepareStatement(sql);  
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                String studId = rs.getString("student_id");
                String sFirst = rs.getString("first_name");
                String sLast = rs.getString("last_name");
                studSelection.addItem(studId+" "+sFirst+" "+sLast);
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    /**
     * this method clears the selections for the comboBoxes and text fields on
     * the Add Grades tab.
     * @param evt button click
     */
    
    private void clearSelectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSelectionsActionPerformed
        // TODO add your handling code here:WIDTH
        //set studentSelection to null          these three are JComboBoxes...
        //clear courseSelection somehow
        //set assignmentSelection to null
        gradeEntered.setText("");
        studentSelection.setSelectedIndex(0);
        courseSelection.removeAllItems();
        assignmentSelection.setSelectedIndex(0);
    }//GEN-LAST:event_clearSelectionsActionPerformed

    private void studentSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentSelectionItemStateChanged
        // TODO add your handling code here:
        courseSelection.removeAllItems();
        fillCourseCombo();
    }//GEN-LAST:event_studentSelectionItemStateChanged

    private void stuSelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stuSelItemStateChanged
        // TODO add your handling code here:
        courseSelect.removeAllItems();
        fillDelCourseCombo();
        int studID = Integer.parseInt(String.valueOf(stuSel.getSelectedItem()));
       
        try{
            Connection conn = Db.java_db();
            String sql = "SELECT * FROM courses WHERE student_id = " + studID;
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            delClassTable.setModel(DbUtils.resultSetToTableModel(rs));             
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_stuSelItemStateChanged

    private void deleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseActionPerformed
        // TODO add your handling code here:
        int studID = Integer.parseInt(String.valueOf(stuSel.getSelectedItem()));
       
        try{
            Connection conn = Db.java_db();
            String sql = "SELECT * FROM courses WHERE student_id = " + studID;
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            delClassTable.setModel(DbUtils.resultSetToTableModel(rs));
              
            
        }
        catch(Exception e){
            System.out.println(e);
        }
        int courseID; String p;
        String x = String.valueOf(courseSelect.getSelectedItem());
        if(x.length()>4){
            p = x.substring(0,4);
        }else{
            p =x;
        }
        courseID = Integer.parseInt(p);
        //collects the student_id from combobox
        int sdi = Integer.parseInt(String.valueOf(stuSel.getSelectedItem()));
        
        Login.delClass(sdi, courseID);
        dispCourseTablePop(studID);
        
    }//GEN-LAST:event_deleteCourseActionPerformed

    private void delStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStudentActionPerformed
        // TODO add your handling code here:
        int studID; String q =null;
        String x = String.valueOf(studSelection.getSelectedItem());
        if(x.length()>3){
            q= x.substring(0,1);
        }
        studID = Integer.parseInt(q);
        Login.deleteStudent(studID);
        dispTableInfo();
    }//GEN-LAST:event_delStudentActionPerformed

    private void studSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studSelectionItemStateChanged
        // TODO add your handling code here:
        int studID; String q =null;
        String x = String.valueOf(studSelection.getSelectedItem());
        if(x.length()>3){
            q = x.substring(0,1);
        }
        studID = Integer.parseInt(q);   int i=0;
        try{
            Connection conn = Db.java_db();
            String sql = "select * from courses where student_id="+studID;
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                i++;
            }
        }catch(Exception e){
            System.out.println(e);
        }
        if(i>0){
            warningMessage.setVisible(true);
        }
    }//GEN-LAST:event_studSelectionItemStateChanged

    /**
     * this method will pull the last id from the database, add one to it, and
     * return the new number as the next ID number to be assigned to the new student.
     */
    private int newIDGen(){
        //pull the last id number from the database
        int i = 0;
        try{
            Connection conn = Db.java_db();
            String sql = "SELECT * FROM student_info";
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                i++;
            }
            System.out.println(i);
        }catch(Exception w){
            System.out.println(w);
        }
        
        return i+1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClass;
    private javax.swing.JPanel addGradesPanel;
    private javax.swing.JPanel addNew;
    private javax.swing.JScrollPane allCourseDisp;
    private javax.swing.JScrollPane allStudentDisp;
    private javax.swing.JComboBox<String> assignmentSelection;
    private javax.swing.JButton changeGrade;
    private javax.swing.JButton clear;
    private javax.swing.JButton clearSelections;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JComboBox<String> courseList;
    private javax.swing.JLabel courseSel;
    private javax.swing.JComboBox<String> courseSelect;
    private javax.swing.JLabel courseSelectLabel;
    private javax.swing.JComboBox<String> courseSelection;
    private javax.swing.JTable delClassTable;
    private javax.swing.JButton delStudent;
    private javax.swing.JPanel deleteClass;
    private javax.swing.JButton deleteCourse;
    private javax.swing.JPanel deleteStudent;
    private javax.swing.JLabel dispAllLabel;
    private javax.swing.JTable dispAllTable;
    private javax.swing.JTable dispCourseTable;
    private javax.swing.JLabel examLabel;
    private javax.swing.JButton exit;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel genIDLabel;
    private javax.swing.JTextField gradeEntered;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastName;
    private javax.swing.JButton modStudent;
    private javax.swing.JPanel modify;
    private javax.swing.JTextField passw;
    private javax.swing.JLabel passwLabel;
    private javax.swing.JButton previous;
    private javax.swing.JTable selStudTable;
    private javax.swing.JScrollPane selectStudentDisp;
    private javax.swing.JTextField stuID;
    private javax.swing.JComboBox<String> stuSel;
    private javax.swing.JLabel stuSelect;
    private javax.swing.JTextField studFirstName;
    private javax.swing.JTextField studLastName;
    private javax.swing.JComboBox<String> studSelection;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JComboBox<String> studentSelection;
    private javax.swing.JButton submit;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JLabel warning;
    private javax.swing.JTextArea warningMessage;
    // End of variables declaration//GEN-END:variables
}
